import React, { useCallback, useEffect, useRef, useState } from 'react';
import { useBlocker, useNavigate, useParams } from 'react-router-dom';
import Skeleton from 'react-loading-skeleton';
import 'react-loading-skeleton/dist/skeleton.css';

import { usePdf } from '../../contexts/PdfContext';
import ConfirmationModal from '../../components/ConfirmationModal';
import OrderNavigationTree from '../../components/OrderNavigationTree';
import LabeledInput from '../../components/LabeledInput';
import LabeledSelect from '../../components/LabeledSelect';
import LabeledReactSelect from '../../components/LabeledReactSelect';
import LabeledSwitch from '../../components/LabeledSwitch';
import apiClient from '../../config/apiClient';
import { formatDateTime, fromDateInputToSwedishIso, toSwedishDateInputValue } from '../../helpers/dateUtils';
import { getFileNameFromContentDisposition } from '../../helpers/fileUtils';
import { parseNullableInt } from '../../helpers/numberUtils';

const COMPANY_ID = 1;

const createNewInquiryModel = () => ({
    id: 0,
    companyId: COMPANY_ID,
    calculationId: null,
    autoGenerated: false,
    customerId: null,
    product: '',
    material: '',
    materialThickness: '',
    format: '',
    color: '',
    construction: '',
    customerName: '',
    deliveryAddressName: '',
    deliveryAddress: '',
    deliveryPostalNr: '',
    deliveryPostalAddress: '',
    deliveryCountry: '',
    ourRef: '',
    preparation: '',
    timeOfDelivery: '',
    selectedInquiryRecipientId: null,
    answerDueDate: null,
    hideCustomerInfoOnPrint: false,
    createdAt: null,
    editedAt: null,
    createdBy: null,
    editedBy: null,
    customerDeliveryAddressId: null,
    isFSC: false,
});

const formatDateInputValue = (value) => toSwedishDateInputValue(value);

const renderInquiryMetaRow = (label, value, userName) => {
    if (!value) {
        return null;
    }

    return (
        <div className="grid grid-cols-21 gap-1 mx-2">
            <div className="col-span-5"><span className="font-medium">{label}</span></div>
            <div className="col-span-8">{formatDateTime(value)}</div>
            <div className="col-span-8 text-gray-500">
                {userName && `av ${userName}`}
            </div>
        </div>
    );
};

const renderReadOnlyInfoRow = (label, value) => (
    <div className="">
        <div className="text-tiny tracking-wide text-gray-400">
            {label}
        </div>
        <div className="mt-1 text-xs text-gray-800 break-words">
            {value || 'Saknas'}
        </div>
    </div>
);

const Inquiry = () => {
    const navigate = useNavigate();
    const { id } = useParams();
    const isNewInquiry = id === 'new' || id == null;

    const {
        openPdfPreview,
        setBadges,
        setEmailInfo,
        markStale,
        clearStale,
        showPdfPanel,
        closePdfPreview,
    } = usePdf();

    const [loading, setLoading] = useState(true);
    const [messages, setMessages] = useState([]);
    const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);
    const [showUnsavedWarning, setShowUnsavedWarning] = useState(false);
    const [unsavedWarningReason, setUnsavedWarningReason] = useState('navigate');

    const [inquiry, setInquiry] = useState(null);
    const [originalInquiry, setOriginalInquiry] = useState(null);
    const [selectedSupplierDetails, setSelectedSupplierDetails] = useState(null);
    const [selectedCustomerDetails, setSelectedCustomerDetails] = useState(null);
    const [selectedDeliveryAddressOption, setSelectedDeliveryAddressOption] = useState('');
    const [legacyUserOptions, setLegacyUserOptions] = useState([]);
    const [loadedSupplierDetailsForId, setLoadedSupplierDetailsForId] = useState(null);
    const [loadedCustomerDetailsForId, setLoadedCustomerDetailsForId] = useState(null);
    const skipUnsavedCheckRef = useRef(false);

    const handleBackClick = () => {
        if (window.history.length > 1) {
            navigate(-1);
            return;
        }

        window.close();
    };

    const hasUnsavedChanges = useCallback(() => {
        if (skipUnsavedCheckRef.current) return false;
        if (!inquiry || !originalInquiry) return false;
        return JSON.stringify(inquiry) !== JSON.stringify(originalInquiry);
    }, [inquiry, originalInquiry]);

    const blocker = useBlocker(hasUnsavedChanges);

    useEffect(() => {
        return () => {
            closePdfPreview?.();
        };
    }, [closePdfPreview]);

    useEffect(() => {
        const handleBeforeUnload = (event) => {
            if (!hasUnsavedChanges()) return;

            event.preventDefault();
            event.returnValue = '';
            return '';
        };

        window.addEventListener('beforeunload', handleBeforeUnload);
        return () => window.removeEventListener('beforeunload', handleBeforeUnload);
    }, [hasUnsavedChanges]);

    useEffect(() => {
        if (blocker.state === 'blocked') {
            setUnsavedWarningReason('navigate');
            setShowUnsavedWarning(true);
        }
    }, [blocker.state]);

    useEffect(() => {
        skipUnsavedCheckRef.current = false;
    }, [id]);

    const updateInquiry = useCallback((patch) => {
        markStale();
        setMessages((prev) => prev.filter((message) => message.type !== 'success'));
        setInquiry((prev) => ({ ...prev, ...patch }));
        if (showPdfPanel) {
            closePdfPreview?.();
        }
    }, [closePdfPreview, markStale, showPdfPanel]);

    const handleCustomerDeliveryAddressChange = useCallback((value) => {
        const selectedAddress = selectedCustomerDetails?.deliveryAddresses?.find(
            (item, index) => String(item?.id ?? `virtual-${index}`) === String(value),
        );

        setSelectedDeliveryAddressOption(String(value ?? ''));

        updateInquiry({
            customerDeliveryAddressId: parseNullableInt(selectedAddress?.id),
            deliveryAddressName: selectedAddress?.name ?? '',
            deliveryAddress: selectedAddress?.address ?? '',
            deliveryPostalNr: selectedAddress?.postalNr ?? '',
            deliveryPostalAddress: selectedAddress?.postalAddress ?? '',
            deliveryCountry: selectedAddress?.country ?? '',
        });
    }, [selectedCustomerDetails, updateInquiry]);

    const syncEmailContext = useCallback((currentInquiry) => {
        const selectedSupplierEmail = currentInquiry?.selectedSupplierEmail ?? selectedSupplierDetails?.supplier?.email;
        const selectedCustomerEmail = selectedCustomerDetails?.customer?.email;

        setBadges([
            { text: currentInquiry?.isFSC ? 'FSC' : 'Ej FSC', color: currentInquiry?.isFSC ? '#166534' : '#6b7280' },
            { text: currentInquiry?.hideCustomerInfoOnPrint ? 'Döljer kundinfo' : 'Visar kundinfo', color: currentInquiry?.hideCustomerInfoOnPrint ? '#b45309' : '#2563eb' },
        ]);

        setEmailInfo({
            recipients: selectedSupplierEmail
                ? [{ email: selectedSupplierEmail, doSend: true }]
                : [{ email: '', doSend: true }],
            ccRecipients: selectedCustomerEmail
                ? [{ email: selectedCustomerEmail, doSend: false }]
                : [{ email: '', doSend: false }],
            subject: `Förfrågan ${currentInquiry?.id || ''}`.trim(),
            body: [
                'Hej,',
                '',
                `Bifogar förfrågan ${currentInquiry?.id || ''}.`,
                '',
                'Vänliga hälsningar',
            ].join('\n'),
            inquiryId: Number.isInteger(currentInquiry?.id) ? currentInquiry.id : null,
        });
    }, [selectedCustomerDetails, selectedSupplierDetails, setBadges, setEmailInfo]);

    useEffect(() => {
        if (inquiry) {
            syncEmailContext(inquiry);
        }
    }, [inquiry, syncEmailContext]);

    const getPdf = async ({ ignoreUnsaved = false } = {}) => {
        if (!inquiry?.id) return;

        if (!ignoreUnsaved && hasUnsavedChanges()) {
            setUnsavedWarningReason('print');
            setShowUnsavedWarning(true);
            return;
        }

        openPdfPreview('');

        try {
            const response = await apiClient.get(`/pdf/inquiry/${inquiry.id}`, { responseType: 'blob' });
            const contentDisposition = response.headers['content-disposition'];
            const fileName = getFileNameFromContentDisposition(contentDisposition) || 'inquiry.pdf';
            const blob = response.data;
            const url = URL.createObjectURL(blob);
            openPdfPreview(url, fileName);
        } catch (error) {
            console.error('Failed to get inquiry PDF:', error);
            setMessages((prev) => [
                ...prev.filter((message) => message.type !== 'error'),
                { type: 'error', text: 'Kunde inte skriva ut förfrågan.' },
            ]);
        }
    };

    const handleUnsavedWarningConfirm = () => {
        setShowUnsavedWarning(false);
        if (unsavedWarningReason === 'print') {
            getPdf({ ignoreUnsaved: true });
            return;
        }

        blocker.proceed();
    };

    const handleUnsavedWarningAbort = () => {
        setShowUnsavedWarning(false);
        if (blocker.state === 'blocked') {
            blocker.reset();
        }
    };

    const buildInquiryPayload = (source) => ({
        companyId: parseNullableInt(source?.companyId) ?? COMPANY_ID,
        calculationId: parseNullableInt(source?.calculationId),
        autoGenerated: Boolean(source?.autoGenerated),
        customerId: parseNullableInt(source?.customerId),
        product: source?.product ?? null,
        material: source?.material ?? null,
        materialThickness: source?.materialThickness ?? null,
        format: source?.format ?? null,
        color: source?.color ?? null,
        construction: source?.construction ?? null,
        customerName: source?.customerName ?? null,
        deliveryAddressName: source?.deliveryAddressName ?? null,
        deliveryAddress: source?.deliveryAddress ?? null,
        deliveryPostalNr: source?.deliveryPostalNr ?? null,
        deliveryPostalAddress: source?.deliveryPostalAddress ?? null,
        deliveryCountry: source?.deliveryCountry ?? null,
        ourRef: source?.ourRef ?? null,
        preparation: source?.preparation ?? null,
        timeOfDelivery: source?.timeOfDelivery ?? null,
        selectedInquiryRecipientId: parseNullableInt(source?.selectedInquiryRecipientId),
        selectedRecipientYourRef: source?.selectedRecipientYourRef ?? null,
        selectedRecipientTermsOfDelivery: source?.selectedRecipientTermsOfDelivery ?? null,
        selectedRecipientTermsOfPayment: source?.selectedRecipientTermsOfPayment ?? null,
        selectedRecipientLanguageId: parseNullableInt(source?.selectedRecipientLanguageId),
        answerDueDate: source?.answerDueDate ?? null,
        hideCustomerInfoOnPrint: Boolean(source?.hideCustomerInfoOnPrint),
        createdAt: source?.createdAt ?? null,
        editedAt: source?.editedAt ?? null,
        createdBy: parseNullableInt(source?.createdBy),
        editedBy: parseNullableInt(source?.editedBy),
        customerDeliveryAddressId: parseNullableInt(source?.customerDeliveryAddressId),
        isFSC: Boolean(source?.isFSC),
        inquiryRowIds: Array.isArray(source?.inquiryRows)
            ? source.inquiryRows
                .map((row) => parseNullableInt(row?.id))
                .filter((rowId) => rowId && rowId > 0)
            : [],
    });

    const handleDeleteRow = (rowId) => {
        updateInquiry({ inquiryRows: (inquiry?.inquiryRows ?? []).filter((row) => row.id !== rowId) });
    };

    const handleSave = async () => {
        if (!inquiry) return;

        try {
            const payload = buildInquiryPayload(inquiry);
            const inquiryId = parseNullableInt(inquiry?.id);
            const isCreatingNew = !(inquiryId && inquiryId > 0);

            const response = inquiryId && inquiryId > 0
                ? await apiClient.put(`/inquiries/${inquiryId}`, payload)
                : await apiClient.post('/inquiries', payload);

            const savedInquiry = response.data;
            setInquiry(savedInquiry ?? null);
            setOriginalInquiry(structuredClone(savedInquiry));
            clearStale();
            setMessages((prev) => [
                ...prev.filter((message) => message.type !== 'success'),
                { type: 'success', text: 'Förfrågan sparades.' },
            ]);

            if (isCreatingNew && savedInquiry?.id) {
                skipUnsavedCheckRef.current = true;
                navigate(`/order/inquiries/${savedInquiry.id}`, { replace: true });
            }
        } catch (error) {
            console.error('Failed to save inquiry:', error);
            setMessages((prev) => [
                ...prev.filter((message) => message.type !== 'error'),
                { type: 'error', text: 'Kunde inte spara förfrågan.' },
            ]);
        }
    };

    const handleDelete = async () => {
        setShowDeleteConfirm(false);

        try {
            await apiClient.delete(`/inquiries/${inquiry.id}`);
            navigate('/order/inquiries');
        } catch (error) {
            console.error('Failed to delete inquiry:', error);
            setMessages((prev) => [
                ...prev.filter((message) => message.type !== 'error'),
                { type: 'error', text: 'Kunde inte radera förfrågan.' },
            ]);
        }
    };

    useEffect(() => {
        const controller = new AbortController();

        const loadInquiry = async () => {
            setLoading(true);

            try {
                setSelectedSupplierDetails(null);

                if (isNewInquiry) {
                    const emptyInquiry = createNewInquiryModel();
                    setInquiry(emptyInquiry);
                    setOriginalInquiry(structuredClone(emptyInquiry));
                } else {
                    const response = await apiClient.get(`/inquiries/${id}`, { signal: controller.signal });
                    const data = response.data;
                    setInquiry(data ?? null);
                    setOriginalInquiry(structuredClone(data));
                }

                clearStale();
            } catch (error) {
                if (error.code === 'ERR_CANCELED') return;
                console.error('Failed to load inquiry:', error);
                setInquiry(null);
            } finally {
                if (!controller.signal.aborted) {
                    setLoading(false);
                }
            }
        };

        loadInquiry();
        return () => controller.abort();
    }, [clearStale, id, isNewInquiry]);

    useEffect(() => {
        const supplierId = parseNullableInt(inquiry?.selectedSupplierId);

        if (!supplierId || supplierId <= 0) {
            setSelectedSupplierDetails(null);
            setLoadedSupplierDetailsForId(null);
            return;
        }

        const controller = new AbortController();

        const loadSupplierDetails = async () => {
            try {
                const response = await apiClient.get(`/suppliers/${supplierId}/details`, { signal: controller.signal });
                setSelectedSupplierDetails(response?.data ?? null);
                setLoadedSupplierDetailsForId(supplierId);
            } catch (error) {
                if (error?.code === 'ERR_CANCELED') return;
                console.error('Failed to load supplier details:', error);
                setSelectedSupplierDetails(null);
                setLoadedSupplierDetailsForId(supplierId);
            }
        };

        loadSupplierDetails();

        return () => controller.abort();
    }, [inquiry?.selectedSupplierId]);

    useEffect(() => {
        const customerId = parseNullableInt(inquiry?.customerId);

        if (!customerId || customerId <= 0) {
            setSelectedCustomerDetails(null);
            setLoadedCustomerDetailsForId(null);
            return;
        }

        const controller = new AbortController();

        const loadCustomerDetails = async () => {
            try {
                const response = await apiClient.get(`/customers/${customerId}`, { signal: controller.signal });
                setSelectedCustomerDetails(response?.data ?? null);
                setLoadedCustomerDetailsForId(customerId);
            } catch (error) {
                if (error?.code === 'ERR_CANCELED') return;
                console.error('Failed to load customer details:', error);
                setSelectedCustomerDetails(null);
                setLoadedCustomerDetailsForId(customerId);
            }
        };

        loadCustomerDetails();

        return () => controller.abort();
    }, [inquiry?.customerId]);

    useEffect(() => {
        const controller = new AbortController();

        const loadLegacyUserOptions = async () => {
            try {
                const response = await apiClient.get('/legacyusers/active-options', { signal: controller.signal });
                const options = Array.isArray(response?.data)
                    ? response.data
                        .map((item) => ({
                            id: item?.id ?? item?.name ?? '',
                            name: item?.name ?? item?.id ?? '',
                        }))
                        .filter((item) => item.id && item.name)
                    : [];

                setLegacyUserOptions(options);
            } catch (error) {
                if (error?.code === 'ERR_CANCELED') return;
                console.error('Failed to load legacy user options:', error);
                setLegacyUserOptions([]);
            }
        };

        loadLegacyUserOptions();

        return () => controller.abort();
    }, []);

    useEffect(() => {
        const customerDeliveryAddressId = parseNullableInt(inquiry?.customerDeliveryAddressId);
        setSelectedDeliveryAddressOption(customerDeliveryAddressId ? String(customerDeliveryAddressId) : '');
    }, [inquiry?.customerDeliveryAddressId, inquiry?.customerId]);

    const supplierId = parseNullableInt(inquiry?.selectedSupplierId);
    const customerId = parseNullableInt(inquiry?.customerId);
    const isSupplierDetailsLoading = Boolean(supplierId && supplierId > 0 && loadedSupplierDetailsForId !== supplierId);
    const isCustomerDetailsLoading = Boolean(customerId && customerId > 0 && loadedCustomerDetailsForId !== customerId);

    if (loading || isSupplierDetailsLoading || isCustomerDetailsLoading) {
        return (
            <div className="pl-10 space-y-4 pt-1 ml-80 mr-60">
                <Skeleton height={30} width={420} className='mb-5' />
                <Skeleton height={220} />
                <Skeleton height={180} />
                <Skeleton height={160} />
            </div>
        );
    }

    if (!inquiry) {
        return (
            <div className="pt-2 text-sm text-red-700">
                Kunde inte ladda förfrågan.
                <button
                    type="button"
                    onClick={() => navigate('/order/inquiries')}
                    className="ml-4 rounded-sm border border-gray-300 bg-white px-3 py-1 text-xs text-gray-700 hover:bg-gray-100"
                >
                    Tillbaka
                </button>
            </div>
        );
    }

    const supplierContactPersonItems = Array.isArray(selectedSupplierDetails?.contactPersons)
        ? selectedSupplierDetails.contactPersons
            .map((item) => {
                const name = item?.name || item?.supplierContactPersonName || item?.contactPerson || '';

                return {
                    id: name,
                    name,
                };
            })
            .filter((item) => item.name)
        : [];
    const supplierLanguageItems = Array.isArray(selectedSupplierDetails?.languages)
        ? (inquiry?.selectedRecipientLanguageId && inquiry?.selectedRecipientLanguageName
            ? [
                ...selectedSupplierDetails.languages,
                {
                    id: inquiry.selectedRecipientLanguageId,
                    name: inquiry.selectedRecipientLanguageName,
                },
            ].filter((item, index, array) => index === array.findIndex((x) => String(x.id) === String(item.id)))
            : selectedSupplierDetails.languages)
        : [];
    const customerDeliveryAddressItems = Array.isArray(selectedCustomerDetails?.deliveryAddresses)
        ? selectedCustomerDetails.deliveryAddresses.map((item, index) => {
            const addressSummary = [item?.address, item?.postalNr, item?.postalAddress, item?.country]
                .filter((part) => typeof part === 'string' && part.trim().length > 0)
                .join(', ');

            return {
                id: item?.id ?? `virtual-${index}`,
                name: item?.name || addressSummary || `Leveransadress ${index + 1}`,
            };
        })
        : [];

    return (
        <div className="relative flex flex-col h-full">
            <ConfirmationModal
                isOpen={showDeleteConfirm}
                onClose={() => setShowDeleteConfirm(false)}
                onConfirm={handleDelete}
                title="RADERA FÖRFRÅGAN"
                message={`Är du säker på att du vill radera förfrågan ${inquiry.id}? Åtgärden kan inte ångras.`}
                confirmText="Radera"
                cancelText="Avbryt"
                isDestructive={true}
            />

            <ConfirmationModal
                isOpen={showUnsavedWarning}
                onClose={handleUnsavedWarningAbort}
                onConfirm={handleUnsavedWarningConfirm}
                title="Osparade ändringar"
                message={unsavedWarningReason === 'print'
                    ? 'Du har osparade ändringar. Spara förfrågan innan du fortsätter.'
                    : 'Det finns osparade ändringar, vill du ändå fortsätta?'}
                confirmText={unsavedWarningReason === 'print' ? '' : 'Fortsätt ändå'}
                cancelText="Avbryt"
                isDestructive={false}
            />

            <h2 className="ml-90 text-sm pt-2 pb-2 text-gray-700">
                {inquiry?.id ? (
                    <>Förfrågan <span className="ml-2 text-red-500">{inquiry.id}</span></>
                ) : (
                    'Ny förfrågan'
                )}
            </h2>

            <div className="flex h-full items-stretch">
                <div className="flex flex-col w-80 shrink-0 border-r border-gray-300 px-2 py-2 mb-5 mr-5">
                    <div className="space-y-3">
                        <h2 className="text-sm text-center text-gray-700">Info</h2>
                        <div className="space-y-2 text-xs text-gray-600">
                            {renderInquiryMetaRow('Skapad:', inquiry?.createdAt, inquiry?.createdByUserName)}
                            {renderInquiryMetaRow('Redigerad:', inquiry?.editedAt, inquiry?.editedByUserName)}
                            {/* {inquiry?.createdAt && (
                                <div className="grid grid-cols-5 gap-4 mx-2">
                                    <div className="col-span-1"><span className="font-medium">Skapad:</span></div>
                                    <div className="col-span-4">{formatDateTime(inquiry.createdAt)}</div>
                                </div>
                            )}
                            {inquiry?.editedAt && (
                                <div className="grid grid-cols-5 gap-4 mx-2">
                                    <div className="col-span-1"><span className="font-medium">Redigerad:</span></div>
                                    <div className="col-span-4">{formatDateTime(inquiry.editedAt)}</div>
                                </div>
                            )} */}
                            {/* <div className="grid grid-cols-5 gap-4 mx-2">
                                <div className="col-span-1"><span className="font-medium">Kund:</span></div>
                                <div className="col-span-4">{selectedCustomer?.name ?? inquiry.customerName ?? 'Saknas'}</div>
                            </div>
                            <div className="grid grid-cols-5 gap-4 mx-2">
                                <div className="col-span-1"><span className="font-medium">Leverantör:</span></div>
                                <div className="col-span-4">{selectedSupplier?.name ?? 'Saknas'}</div>
                            </div>
                            {inquiry?.answerDueDate && (
                                <div className="grid grid-cols-5 gap-4 mx-2">
                                    <div className="col-span-1"><span className="font-medium">Svar senast:</span></div>
                                    <div className="col-span-4">{formatDateTime(inquiry.answerDueDate)}</div>
                                </div>
                            )} */}
                        </div>
                    </div>

                    <OrderNavigationTree
                        entityType="inquiry"
                        entityId={Number.isInteger(inquiry?.id) && inquiry.id > 0 ? inquiry.id : null}
                    />

                    <hr className="mt-5 border-gray-300 dark:border-white" />
                    <h2 className="text-sm text-center text-gray-700 mt-5">Meddelanden</h2>
                    {messages.length === 0 ? (
                        <p className='text-xs text-center font-light mt-4'>Inga meddelanden</p>
                    ) : (
                        <ul className="mt-2 space-y-2">
                            {[...messages].map((message, index) => (
                                <li
                                    key={index}
                                    className={`text-center text-xs p-2 rounded border border-gray-200 ${message.type === 'error'
                                        ? 'bg-red-100 text-red-700'
                                        : message.type === 'warning'
                                            ? 'bg-yellow-100 text-yellow-800'
                                            : 'bg-green-100 text-green-700'
                                        }`}
                                >
                                    {message.text}
                                </li>
                            ))}
                        </ul>
                    )}

                </div>

                <div className="flex-grow ps-4 pe-10 py-2 max-w-350">
                    <div className="flex justify-between w-full mb-5">
                        <div className='flex items-center space-x-4'>
                            <button
                                type='button'
                                onClick={handleBackClick}
                                className="shadow-md/30 text-xs text-white bg-gray-500 hover:bg-gray-700 px-5 p-[5px]"
                            >
                                Tillbaka
                            </button>
                            <button
                                type='button'
                                onClick={handleSave}
                                className="shadow-md/30 text-xs text-white bg-lime-700 hover:bg-lime-900 px-5 p-[5px]"
                            >
                                Spara
                            </button>
                            {inquiry?.id !== 0 && (
                                <button
                                    type="button"
                                    onClick={getPdf}
                                    className="shadow-md/30 text-xs text-gray bg-blue-200 hover:bg-blue-300 px-4 py-[5px] ml-10"
                                >
                                    Skriv ut
                                </button>
                            )}
                        </div>
                        <div className='flex items-center space-x-4'>
                            {inquiry?.id !== 0 && (
                                <button
                                    type="button"
                                    onClick={() => setShowDeleteConfirm(true)}
                                    className="shadow-md/30 text-xs text-white bg-red-700 hover:bg-red-800 px-5 p-[5px]"
                                >
                                    Radera
                                </button>
                            )}
                        </div>
                    </div>

                    <div className="ml-[-5px] w-200 mb-4 rounded-sm border border-gray-200 bg-gradient-to-br from-slate-50 via-white to-slate-100 px-5 py-4 shadow-sm">
                        {/* <div className="flex items-center justify-between gap-4">
                            <div>
                                <h3 className="text-sm font-semibold text-gray-800">Produktinformation</h3>
                                <p className="mt-1 text-xs text-gray-500">Översikt över produktdetaljerna. Denna sektion är endast för visning.</p>
                            </div>
                            <div className="rounded-full border border-gray-200 bg-white px-3 py-1 text-[11px] font-medium uppercase tracking-wide text-gray-500">
                                Read-only
                            </div>
                        </div> */}

                        <div className="grid grid-cols-[3fr_1fr]">
                            <div className="mt-0 grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-3">
                                {renderReadOnlyInfoRow('Produkt', inquiry?.product)}
                                {renderReadOnlyInfoRow('Material', inquiry?.material)}
                                {/* {renderReadOnlyInfoRow('Tjocklek', inquiry?.materialThickness)} */}
                                {renderReadOnlyInfoRow('Format', inquiry?.format)}
                                {renderReadOnlyInfoRow('Färg', inquiry?.color)}
                                {renderReadOnlyInfoRow('Konstruktion', inquiry?.construction)}
                                {renderReadOnlyInfoRow('FSC', inquiry?.isFSC ? 'Ja' : 'Nej')}
                            </div>
                            <div>
                                {renderReadOnlyInfoRow('Packning', 'todo')}
                            </div>
                        </div>
                    </div>

                    <div className="mt-10 grid w-full grid-cols-[max-content_minmax(0,1fr)] gap-x-25">
                        <span>
                            <div className="grid grid-cols-[350px_350px] gap-x-20 gap-y-8">

                                <span>
                                    <p className='text-sm font-semibold text-gray-500 mb-4 pb-2 text-center border-b border-gray-300'>{inquiry?.customerName || ''}</p>
                                    <LabeledReactSelect
                                        name='customerDeliveryAddressId'
                                        label='Lev. adress'
                                        value={inquiry?.customerDeliveryAddressId || ''}
                                        items={customerDeliveryAddressItems}
                                        onChange={handleCustomerDeliveryAddressChange}
                                        labelWidth="w-20"
                                        margintop="2"
                                        allowRawValueLabel
                                    />
                                    <LabeledInput
                                        label=''
                                        value={inquiry?.deliveryAddressName || ''}
                                        onChange={(value) => updateInquiry({ deliveryAddressName: value })}
                                        labelWidth="w-20"
                                        margintop="0"
                                    />
                                    <LabeledInput
                                        label=''
                                        value={inquiry?.deliveryAddress || ''}
                                        onChange={(value) => updateInquiry({ deliveryAddress: value })}
                                        labelWidth="w-20"
                                        margintop="0"
                                    />
                                    <div className='flex space-x-1 w-full mt-[0px]'>
                                        <LabeledInput
                                            name='deliveryPostalNr'
                                            label=''
                                            value={inquiry?.deliveryPostalNr || ''}
                                            onChange={(value) => updateInquiry({ deliveryPostalNr: value })}
                                            labelWidth="w-20"
                                            inputWidth="w-25"
                                            margintop="0"
                                            placeholder=""
                                        />
                                        <div className="w-full">
                                            <input
                                                name="deliveryPostalAddress"
                                                value={inquiry?.deliveryPostalAddress || ''}
                                                onChange={(value) => updateInquiry({ deliveryPostalAddress: value })}
                                                className='text-xs w-full border border-gray-300 rounded-sm px-2 py-1 focus:outline-none bg-white'
                                            />

                                        </div>
                                    </div>
                                    <LabeledInput
                                        label=''
                                        value={inquiry?.deliveryCountry || ''}
                                        onChange={(value) => updateInquiry({ deliveryCountry: value })}
                                        labelWidth="w-20"
                                        margintop="0"
                                    />
                                    <div className='flex items-center space-x-1 w-50 text-xs pt-[1px] pb-1'>
                                        <LabeledSwitch
                                            field='hideCustomerInfoOnPrint'
                                            name='hideCustomerInfoOnPrint'
                                            label='Dölj på utskrift'
                                            value={inquiry?.hideCustomerInfoOnPrint || false}
                                            onChange={(rowId, field, checked) => updateInquiry({ [field]: checked })}
                                            labelWidth="w-20"
                                            marginTop={0}
                                        />
                                    </div>
                                    <LabeledInput
                                        label='Leveranstid'
                                        value={inquiry?.timeOfDelivery || ''}
                                        onChange={(value) => updateInquiry({ timeOfDelivery: value })}
                                        labelWidth="w-20"
                                        margintop="0"
                                    />
                                    <LabeledInput
                                        label='Verktyg'
                                        value={inquiry?.preparation || ''}
                                        onChange={(value) => updateInquiry({ preparation: value })}
                                        labelWidth="w-20"
                                        margintop="0"
                                    />
                                    <div className='flex items-center space-x-1 w-50 text-xs pt-[1px]'>
                                        <label className="w-20 flex-none text-xs text-gray-700">Svar senast</label>
                                        <input
                                            type="date"
                                            value={formatDateInputValue(inquiry?.answerDueDate)}
                                            onChange={(event) => updateInquiry({ answerDueDate: fromDateInputToSwedishIso(event.target.value) })}
                                            className="w-30 text-xs px-2 py-1 border border-gray-300 bg-white rounded-sm focus:outline-none focus:ring-1 focus:ring-green-500"
                                        />
                                    </div>
                                </span>

                                <span>
                                    <p className='text-sm font-semibold text-gray-500 mb-4 pb-2 text-center border-b border-gray-300'>{inquiry?.selectedSupplierName ?? 'Saknas'}</p>
                                    <LabeledReactSelect
                                        name='selectedRecipientYourRef'
                                        label='Er referens'
                                        value={inquiry?.selectedRecipientYourRef || ''}
                                        items={supplierContactPersonItems}
                                        onChange={(value) => updateInquiry({ selectedRecipientYourRef: value || '' })}
                                        labelWidth="w-20"
                                        margintop="2"
                                        allowRawValueLabel
                                    />
                                    <LabeledReactSelect
                                        name='ourRef'
                                        label='Vår referens'
                                        value={inquiry?.ourRef || ''}
                                        items={legacyUserOptions}
                                        onChange={(value) => updateInquiry({ ourRef: value || '' })}
                                        labelWidth="w-20"
                                        margintop="0"
                                        allowRawValueLabel
                                    />
                                    <LabeledInput
                                        label='Lev.villkor'
                                        value={inquiry?.selectedRecipientTermsOfDelivery || ''}
                                        onChange={(value) => updateInquiry({ selectedRecipientTermsOfDelivery: value })}
                                        labelWidth="w-20"
                                        margintop="0"
                                    />
                                    <LabeledInput
                                        label='Bet.villkor'
                                        value={inquiry?.selectedRecipientTermsOfPayment || ''}
                                        onChange={(value) => updateInquiry({ selectedRecipientTermsOfPayment: value })}
                                        labelWidth="w-20"
                                        margintop="0"
                                    />
                                    <LabeledSelect
                                        name='selectedRecipientLanguageId'
                                        label='Språk'
                                        value={inquiry?.selectedRecipientLanguageId || ''}
                                        items={supplierLanguageItems}
                                        onChange={(value) => updateInquiry({ selectedRecipientLanguageId: parseNullableInt(value) })}
                                        labelWidth="w-20"
                                        margintop="0"
                                    />

                                </span>
                            </div>

                        </span>
                    </div>

                    <div className="mt-10 w-[700px]">
                        <p className="text-sm font-semibold text-gray-500 mb-1 pb-2 text-center border-b border-gray-300">Förfråganrader</p>
                        {Array.isArray(inquiry?.inquiryRows) && inquiry.inquiryRows.length > 0 && (
                            <table className="w-full text-xs border-collapse">
                                <thead>
                                    <tr className="border-b border-gray-300">
                                        <th className="text-left font-medium text-gray-500 tracking-wide py-1 pr-6">Upplaga</th>
                                        <th className="text-left font-medium text-gray-500 tracking-wide py-1 pr-6">{`Inköpspris ${inquiry?.purchaseCurrencyName || ''}`.trim()}</th>
                                        <th className="text-left font-medium text-gray-500 tracking-wide py-1 pr-6">{`Frakt ${inquiry?.salesCurrencyName || ''}`.trim()}</th>
                                        <th className="text-left font-medium text-gray-500 tracking-wide py-1">Ta bort</th>
                                    </tr>
                                    <tr>
                                        <td colSpan={4}><div className="border-t border-gray-300" /></td>
                                    </tr>
                                </thead>
                                <tbody>
                                    {inquiry.inquiryRows.map((row) => (
                                        <tr key={row.id} className="border-b border-gray-100">
                                            <td className="py-1 pr-6 font-bold">{row.edition ?? ''}</td>
                                            <td className="py-1 pr-6 font-bold">{row.purchasePrice ?? ''}</td>
                                            <td className="py-1 pr-6 font-bold">{row.freight ?? ''}</td>
                                            <td className="py-1">
                                                <button
                                                    type="button"
                                                    onClick={() => handleDeleteRow(row.id)}
                                                    className="text-gray-600 hover:text-red-700"
                                                >
                                                    Ta bort
                                                </button>
                                            </td>
                                        </tr>
                                    ))}
                                </tbody>
                            </table>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
};

export default Inquiry;
