import React, { useCallback, useEffect, useRef, useState } from 'react';
import { useBlocker, useNavigate, useParams } from 'react-router-dom';
import Skeleton from 'react-loading-skeleton';
import 'react-loading-skeleton/dist/skeleton.css';

import { usePdf } from '../../contexts/PdfContext';
import ConfirmationModal from '../../components/ConfirmationModal';
import OrderNavigationTree from '../../components/OrderNavigationTree';
import OrderCost from '../../components/OrderCost';
import LabeledInput from '../../components/LabeledInput';
import LabeledReactSelect from '../../components/LabeledReactSelect';
import LabeledSwitch from '../../components/LabeledSwitch';
import apiClient, { logApiRequestSummary } from '../../config/apiClient';
import { formatDateTime, fromDateInputToSwedishIso, toSwedishDateInputValue } from '../../helpers/dateUtils';
import { getFileNameFromContentDisposition } from '../../helpers/fileUtils';
import { parseNullableInt } from '../../helpers/numberUtils';
import { getSharedRequest } from '../../helpers/sharedRequest';
import LabeledTextArea from '../../components/LabeledTextArea';

const COMPANY_ID = 1;

const toArray = (value) => (Array.isArray(value) ? value : []);

const toInputValue = (value) => (value == null ? '' : String(value));

const parseNullableDecimal = (value) => {
    if (value == null || value === '') return null;
    const normalized = String(value).trim().replace(',', '.');
    if (!normalized) return null;
    const parsed = Number(normalized);
    return Number.isFinite(parsed) ? parsed : null;
};

const makeTempId = () => `temp-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;

const mapApiOrderCostToEditable = (row) => ({
    localId: row?.id ? String(row.id) : makeTempId(),
    id: row?.id ?? null,
    quotationId: row?.quotationId ?? null,
    customerOrderId: row?.customerOrderId ?? null,
    supplierOrderId: row?.supplierOrderId ?? null,
    costId: row?.costId ?? null,
    doDebit: Boolean(row?.doDebit),
    nrOf: toInputValue(row?.nrOf),
    inPrice: toInputValue(row?.inPrice),
    inPriceCurrencyId: parseNullableInt(row.inPriceCurrencyId),
    inPriceAttested: toInputValue(row?.inPriceAttested),
    outPrice: toInputValue(row?.outPrice),
    markup: row?.markup ?? null,
    note: row?.note ?? '',
    supplierName: row?.supplierName ?? '',
    invoiceId: row?.invoiceId ?? null,
    invoiceRowId: row?.invoiceRowId ?? null,
    doPrintOnQuotation: Boolean(row?.doPrintOnQuotation),
    doPrintOnCustomerOrder: Boolean(row?.doPrintOnCustomerOrder),
    doPrintOnSupplierOrder: Boolean(row?.doPrintOnSupplierOrder),
    doInvoiceSeparately: Boolean(row?.doInvoiceSeparately),
    doInvoiceSeparatelyImmediately: Boolean(row?.doInvoiceSeparatelyImmediately),
    isCostInvoicedSeparately: Boolean(row?.isCostInvoicedSeparately),
});

const buildOrderCostPayload = (row) => ({
    id: row.id ?? null,
    customerOrderId: row.customerOrderId ?? null,
    supplierOrderId: row.supplierOrderId ?? null,
    costId: parseNullableInt(row.costId),
    doDebit: Boolean(row.doDebit),
    nrOf: parseNullableDecimal(row.nrOf),
    inPrice: parseNullableDecimal(row.inPrice),
    inPriceCurrencyId: parseNullableInt(row.inPriceCurrencyId),
    inPriceAttested: parseNullableDecimal(row.inPriceAttested),
    outPrice: parseNullableDecimal(row.outPrice),
    invoiceId: parseNullableInt(row.invoiceId),
    note: row.note || null,
    supplierName: row.supplierName || null,
    doPrintOnQuotation: Boolean(row.doPrintOnQuotation),
    doPrintOnCustomerOrder: Boolean(row.doPrintOnCustomerOrder),
    doPrintOnSupplierOrder: Boolean(row.doPrintOnSupplierOrder),
    doInvoiceSeparately: Boolean(row.doInvoiceSeparately),
    doInvoiceSeparatelyImmediately: Boolean(row.doInvoiceSeparatelyImmediately),
    isCostInvoicedSeparately: Boolean(row.isCostInvoicedSeparately),
});

const createNewQuotationModel = () => ({
    id: 0,
    companyId: COMPANY_ID,
    calculationId: null,
    autoGenerated: false,
    customerId: null,
    product: '',
    material: '',
    materialThickness: '',
    format: '',
    color: '',
    construction: '',
    customerName: '',
    deliveryAddressName: '',
    deliveryAddress: '',
    deliveryPostalNr: '',
    deliveryPostalAddress: '',
    deliveryCountry: '',
    ourReference: '',
    yourReference: '',
    message: '',
    termsOfDelivery: '',
    termsOfPayment: '',
    timeOfDelivery: '',
    date: null,
    hideDeliveryAddressOnPrint: false,
    createdAt: null,
    editedAt: null,
    createdBy: null,
    editedBy: null,
    customerDeliveryAddressId: null,
    eurPallet: false,
    nrOfEurPallet: null,
    eurPalletValue: null,
    palletFormatId: null,
    isFSC: false,
    quotationRows: [],
    orderCosts: [],
});

const formatDateInputValue = (value) => toSwedishDateInputValue(value);

const renderQuotationMetaRow = (label, value, userName) => {
    if (!value) {
        return null;
    }

    return (
        <div className="grid grid-cols-21 gap-1 mx-2">
            <div className="col-span-5"><span className="font-medium">{label}</span></div>
            <div className="col-span-8">{formatDateTime(value)}</div>
            <div className="col-span-8 text-gray-500">
                {userName && `av ${userName}`}
            </div>
        </div>
    );
};

const renderReadOnlyInfoRow = (label, value) => (
    <div className="">
        <div className="text-tiny tracking-wide text-gray-400">
            {label}
        </div>
        <div className="mt-1 text-xs text-gray-800 break-words">
            {value || 'Saknas'}
        </div>
    </div>
);

const Quotation = () => {
    const navigate = useNavigate();
    const { id } = useParams();
    const isNewQuotation = id === 'new' || id == null;

    const {
        openPdfPreview,
        setBadges,
        setEmailInfo,
        markStale,
        clearStale,
        showPdfPanel,
        closePdfPreview,
    } = usePdf();

    const [loading, setLoading] = useState(true);
    const [messages, setMessages] = useState([]);
    const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);
    const [showUnsavedWarning, setShowUnsavedWarning] = useState(false);
    const [unsavedWarningReason, setUnsavedWarningReason] = useState('navigate');

    const [quotation, setQuotation] = useState(null);
    const [originalQuotation, setOriginalQuotation] = useState(null);
    const [selectedSupplierDetails, setSelectedSupplierDetails] = useState(null);
    const [selectedCustomerDetails, setSelectedCustomerDetails] = useState(null);
    const [, setSelectedDeliveryAddressOption] = useState('');
    const [legacyUserOptions, setLegacyUserOptions] = useState([]);
    const [loadedSupplierDetailsForId, setLoadedSupplierDetailsForId] = useState(null);
    const [loadedCustomerDetailsForId, setLoadedCustomerDetailsForId] = useState(null);
    const [orderCostOptions, setOrderCostOptions] = useState([]);
    const [currencyOptions, setCurrencyOptions] = useState([]);
    const [palletFormatOptions, setPalletFormatOptions] = useState([]);
    const skipUnsavedCheckRef = useRef(false);
    const quotationLoadStartedAtRef = useRef(null);

    const handleBackClick = () => {
        if (window.history.length > 1) {
            navigate(-1);
            return;
        }

        window.close();
    };

    const hasUnsavedChanges = useCallback(() => {
        if (skipUnsavedCheckRef.current) return false;
        if (!quotation || !originalQuotation) return false;
        return JSON.stringify(quotation) !== JSON.stringify(originalQuotation);
    }, [quotation, originalQuotation]);

    const blocker = useBlocker(hasUnsavedChanges);

    useEffect(() => {
        return () => {
            closePdfPreview?.();
        };
    }, [closePdfPreview]);

    useEffect(() => {
        const handleBeforeUnload = (event) => {
            if (!hasUnsavedChanges()) return;

            event.preventDefault();
            event.returnValue = '';
            return '';
        };

        window.addEventListener('beforeunload', handleBeforeUnload);
        return () => window.removeEventListener('beforeunload', handleBeforeUnload);
    }, [hasUnsavedChanges]);

    useEffect(() => {
        if (blocker.state === 'blocked') {
            setShowUnsavedWarning(true);
        }
    }, [blocker.state]);

    useEffect(() => {
        skipUnsavedCheckRef.current = false;
    }, [id]);

    const getPdf = useCallback(async ({ ignoreUnsaved = false } = {}) => {
        if (!quotation?.id) return null;

        if (!ignoreUnsaved && hasUnsavedChanges()) {
            setUnsavedWarningReason('print');
            setShowUnsavedWarning(true);
            return null;
        }

        openPdfPreview('');

        try {
            const response = await apiClient.get(`/pdf/quotation/${quotation.id}`, {
                responseType: 'blob',
            });
            const contentDisposition = response.headers['content-disposition'];
            const fileName = getFileNameFromContentDisposition(contentDisposition) || `quotation_${quotation.id}.pdf`;
            const blob = response.data;
            const url = URL.createObjectURL(blob);
            openPdfPreview(url, fileName);
            return { url, fileName };
        } catch (error) {
            console.error('Failed to get quotation PDF:', error);
            setMessages((prev) => [
                ...prev.filter((message) => message.type !== 'error'),
                { type: 'error', text: 'Kunde inte ladda offert-PDF.' },
            ]);
            return null;
        }
    }, [hasUnsavedChanges, openPdfPreview, quotation?.id]);

    const updateQuotation = useCallback((patch) => {
        markStale();
        setMessages((prev) => prev.filter((message) => message.type !== 'success'));
        setQuotation((prev) => ({ ...prev, ...patch }));
        if (showPdfPanel) {
            closePdfPreview?.();
        }
    }, [closePdfPreview, markStale, showPdfPanel]);

    const handleCustomerDeliveryAddressChange = useCallback((value) => {
        const selectedAddress = selectedCustomerDetails?.deliveryAddresses?.find(
            (item, index) => String(item?.id ?? `virtual-${index}`) === String(value),
        );

        setSelectedDeliveryAddressOption(String(value ?? ''));

        updateQuotation({
            customerDeliveryAddressId: parseNullableInt(selectedAddress?.id),
            deliveryAddressName: selectedAddress?.name ?? '',
            deliveryAddress: selectedAddress?.address ?? '',
            deliveryPostalNr: selectedAddress?.postalNr ?? '',
            deliveryPostalAddress: selectedAddress?.postalAddress ?? '',
            deliveryCountry: selectedAddress?.country ?? '',
        });
    }, [selectedCustomerDetails, updateQuotation]);

    const syncEmailContext = useCallback((currentQuotation) => {
        const selectedSupplierEmail = currentQuotation?.selectedSupplierEmail ?? selectedSupplierDetails?.supplier?.email;
        const selectedCustomerEmail = selectedCustomerDetails?.customer?.email;

        setBadges([
            { text: currentQuotation?.isFSC ? 'FSC' : 'Ej FSC', color: currentQuotation?.isFSC ? '#166534' : '#6b7280' },
            { text: currentQuotation?.hideDeliveryAddressOnPrint ? 'Döljer leveransadress' : 'Visar leveransadress', color: currentQuotation?.hideDeliveryAddressOnPrint ? '#b45309' : '#2563eb' },
        ]);

        setEmailInfo({
            recipients: selectedSupplierEmail
                ? [{ email: selectedSupplierEmail, doSend: true }]
                : [{ email: '', doSend: true }],
            ccRecipients: selectedCustomerEmail
                ? [{ email: selectedCustomerEmail, doSend: false }]
                : [{ email: '', doSend: false }],
            subject: `Offert ${currentQuotation?.id || ''}`.trim(),
            body: [
                'Hej,',
                '',
                `Bifogar offert ${currentQuotation?.id || ''}.`,
                '',
                'Vänliga hälsningar',
            ].join('\n'),
            quotationId: Number.isInteger(currentQuotation?.id) ? currentQuotation.id : null,
        });
    }, [selectedCustomerDetails, selectedSupplierDetails, setBadges, setEmailInfo]);

    useEffect(() => {
        if (quotation) {
            syncEmailContext(quotation);
        }
    }, [quotation, syncEmailContext]);

    const handleUnsavedWarningConfirm = () => {
        setShowUnsavedWarning(false);
        if (unsavedWarningReason === 'print') {
            void getPdf({ ignoreUnsaved: true });
            return;
        }

        blocker.proceed();
    };

    const handleUnsavedWarningAbort = () => {
        setShowUnsavedWarning(false);
        setUnsavedWarningReason('navigate');
        if (blocker.state === 'blocked') {
            blocker.reset();
        }
    };

    const buildQuotationPayload = (source) => ({
        companyId: parseNullableInt(source?.companyId) ?? COMPANY_ID,
        calculationId: parseNullableInt(source?.calculationId),
        autoGenerated: Boolean(source?.autoGenerated),
        customerId: parseNullableInt(source?.customerId),
        product: source?.product ?? null,
        material: source?.material ?? null,
        materialThickness: source?.materialThickness ?? null,
        format: source?.format ?? null,
        color: source?.color ?? null,
        construction: source?.construction ?? null,
        customerName: source?.customerName ?? null,
        deliveryAddressName: source?.deliveryAddressName ?? null,
        deliveryAddress: source?.deliveryAddress ?? null,
        deliveryPostalNr: source?.deliveryPostalNr ?? null,
        deliveryPostalAddress: source?.deliveryPostalAddress ?? null,
        deliveryCountry: source?.deliveryCountry ?? null,
        ourReference: source?.ourReference ?? null,
        yourReference: source?.yourReference ?? null,
        message: source?.message ?? null,
        termsOfDelivery: source?.termsOfDelivery ?? null,
        termsOfPayment: source?.termsOfPayment ?? null,
        timeOfDelivery: source?.timeOfDelivery ?? null,
        date: source?.date ?? null,
        hideDeliveryAddressOnPrint: Boolean(source?.hideDeliveryAddressOnPrint),
        eurPallet: Boolean(source?.eurPallet),
        nrOfEurPallet: parseNullableInt(source?.nrOfEurPallet),
        eurPalletValue: parseNullableDecimal(source?.eurPalletValue),
        palletFormatId: parseNullableInt(source?.palletFormatId),
        createdAt: source?.createdAt ?? null,
        editedAt: source?.editedAt ?? null,
        createdBy: parseNullableInt(source?.createdBy),
        editedBy: parseNullableInt(source?.editedBy),
        customerDeliveryAddressId: parseNullableInt(source?.customerDeliveryAddressId),
        isFSC: Boolean(source?.isFSC),
        quotationRowIds: Array.isArray(source?.quotationRows)
            ? source.quotationRows
                .map((row) => parseNullableInt(row?.id))
                .filter((rowId) => rowId && rowId > 0)
            : [],
        orderCosts: toArray(source?.orderCosts)
            .filter((row) => row.costId != null)
            .map(buildOrderCostPayload),
    });

    const handleDeleteRow = (rowId) => {
        updateQuotation({ quotationRows: (quotation?.quotationRows ?? []).filter((row) => row.id !== rowId) });
    };

    const handleOrderCostChange = useCallback((newRows) => {
        updateQuotation({ orderCosts: newRows });
    }, [updateQuotation]);

    const handlePalletRowChange = useCallback((patch) => {
        updateQuotation(patch);
    }, [updateQuotation]);

    const handleSave = async () => {
        if (!quotation) return;

        try {
            const payload = buildQuotationPayload(quotation);
            const quotationId = parseNullableInt(quotation?.id);
            const isCreatingNew = !(quotationId && quotationId > 0);

            const response = quotationId && quotationId > 0
                ? await apiClient.put(`/quotations/${quotationId}`, payload)
                : await apiClient.post('/quotations', payload);

            const savedQuotation = response.data;
            const savedWithEditable = {
                ...savedQuotation,
                orderCosts: toArray(savedQuotation?.orderCosts).map(mapApiOrderCostToEditable),
            };

            setQuotation(savedWithEditable);
            setOriginalQuotation(structuredClone(savedWithEditable));
            clearStale();
            setMessages((prev) => [
                ...prev.filter((message) => message.type !== 'success'),
                { type: 'success', text: 'Offert sparades.' },
            ]);

            if (isCreatingNew && savedQuotation?.id) {
                skipUnsavedCheckRef.current = true;
                navigate(`/order/quotations/${savedQuotation.id}`, { replace: true });
            }
        } catch (error) {
            console.error('Failed to save quotation:', error);
            setMessages((prev) => [
                ...prev.filter((message) => message.type !== 'error'),
                { type: 'error', text: 'Kunde inte spara offert.' },
            ]);
        }
    };

    const handleDelete = async () => {
        setShowDeleteConfirm(false);

        try {
            await apiClient.delete(`/quotations/${quotation.id}`);
            navigate('/order/quotations');
        } catch (error) {
            console.error('Failed to delete quotation:', error);
            setMessages((prev) => [
                ...prev.filter((message) => message.type !== 'error'),
                { type: 'error', text: 'Kunde inte radera offert.' },
            ]);
        }
    };

    const supplierId = parseNullableInt(quotation?.selectedSupplierId);
    const customerId = parseNullableInt(quotation?.customerId);
    const isSupplierDetailsLoading = Boolean(supplierId && supplierId > 0 && loadedSupplierDetailsForId !== supplierId);
    const isCustomerDetailsLoading = Boolean(customerId && customerId > 0 && loadedCustomerDetailsForId !== customerId);

    useEffect(() => {
        let isActive = true;

        const loadQuotation = async () => {
            setLoading(true);
            quotationLoadStartedAtRef.current = Date.now();

            try {
                if (isActive) {
                    setSelectedSupplierDetails(null);
                }

                if (isNewQuotation) {
                    const emptyQuotation = createNewQuotationModel();
                    if (!isActive) return;
                    setQuotation(emptyQuotation);
                    setOriginalQuotation(structuredClone(emptyQuotation));
                } else {
                    const requestKey = `quotations:${id}`;
                    const response = await getSharedRequest(requestKey, () => apiClient.get(`/quotations/${id}`));
                    if (!isActive) return;

                    const data = response.data;
                    const dataWithEditable = {
                        ...data,
                        orderCosts: toArray(data?.orderCosts).map(mapApiOrderCostToEditable),
                    };
                    setQuotation(dataWithEditable ?? null);
                    setOriginalQuotation(structuredClone(dataWithEditable));
                }

                if (isActive) {
                    clearStale();
                }
            } catch (error) {
                console.error('Failed to load quotation:', error);
                if (!isActive) return;
                setQuotation(null);
            } finally {
                if (isActive) {
                    setLoading(false);
                }
            }
        };

        loadQuotation();

        return () => {
            isActive = false;
        };
    }, [clearStale, id, isNewQuotation]);

    useEffect(() => {
        if (loading || isSupplierDetailsLoading || isCustomerDetailsLoading) {
            return;
        }

        const sinceMs = quotationLoadStartedAtRef.current;

        if (!sinceMs) {
            return;
        }

        const title = quotation?.id
            ? `Quotation ${quotation.id} load summary`
            : 'New quotation load summary';

        logApiRequestSummary({
            title,
            sinceMs,
            top: 5,
            include: (entry) => {
                const endpoint = entry?.endpoint || '';

                return endpoint.includes('/quotations')
                    || endpoint.includes('/suppliers/')
                    || endpoint.includes('/customers/')
                    || endpoint.includes('/legacyusers/active-options')
                    || endpoint.includes('/costs/search')
                    || endpoint.includes('/currencies/search')
                    || endpoint.includes('/palletformats/searchwithprices');
            },
        });

        quotationLoadStartedAtRef.current = null;
    }, [isCustomerDetailsLoading, isSupplierDetailsLoading, loading, quotation?.id]);

    useEffect(() => {
        const supplierId = parseNullableInt(quotation?.selectedSupplierId);

        if (!supplierId || supplierId <= 0) {
            setSelectedSupplierDetails(null);
            setLoadedSupplierDetailsForId(null);
            return;
        }

        let isActive = true;

        const loadSupplierDetails = async () => {
            try {
                const requestKey = `suppliers:${supplierId}:details`;
                const response = await getSharedRequest(requestKey, () => apiClient.get(`/suppliers/${supplierId}/details`));
                if (!isActive) return;
                setSelectedSupplierDetails(response?.data ?? null);
                setLoadedSupplierDetailsForId(supplierId);
            } catch (error) {
                console.error('Failed to load supplier details:', error);
                if (!isActive) return;
                setSelectedSupplierDetails(null);
                setLoadedSupplierDetailsForId(supplierId);
            }
        };

        loadSupplierDetails();

        return () => {
            isActive = false;
        };
    }, [quotation?.selectedSupplierId]);

    useEffect(() => {
        let isActive = true;

        const toLegacyUserOptions = (items) => (Array.isArray(items)
            ? items
                .map((item) => ({
                    id: item?.id ?? item?.name ?? '',
                    name: item?.name ?? item?.id ?? '',
                }))
                .filter((item) => item.id && item.name)
            : []);

        const loadFormOptions = async () => {
            try {
                const quotationId = parseNullableInt(id);

                if (!isNewQuotation && quotationId && quotationId > 0) {
                    const requestKey = `quotations:${quotationId}:form-options`;
                    const response = await getSharedRequest(requestKey, () => apiClient.get(`/quotations/${quotationId}/form-options`));
                    const payload = response?.data ?? {};

                    if (!isActive) return;

                    setLegacyUserOptions(toLegacyUserOptions(payload?.users));
                    setOrderCostOptions(toArray(payload?.costs));
                    setCurrencyOptions(toArray(payload?.currencies));
                    setPalletFormatOptions(toArray(payload?.palletFormats));
                    return;
                }

                const [usersRes, costsRes, currenciesRes] = await getSharedRequest('quotations:new:form-options', () => Promise.all([
                    apiClient.get('/legacyusers/active-options'),
                    apiClient.post('/costs/search', {}),
                    apiClient.post('/currencies/search', {
                        pagination: { pageNumber: 1, pageSize: 200 },
                        orderBy: [{ field: 'name', direction: 'asc' }],
                    }),
                ]));

                if (!isActive) return;

                setLegacyUserOptions(toLegacyUserOptions(usersRes?.data));
                setOrderCostOptions(toArray(costsRes?.data));
                setCurrencyOptions(Array.isArray(currenciesRes?.data?.items) ? currenciesRes.data.items : []);
                setPalletFormatOptions([]);
            } catch (error) {
                console.error('Failed to load quotation form options:', error);
                if (!isActive) return;
                setLegacyUserOptions([]);
                setOrderCostOptions([]);
                setCurrencyOptions([]);
                setPalletFormatOptions([]);
            }
        };

        loadFormOptions();

        return () => {
            isActive = false;
        };
    }, [id, isNewQuotation]);

    useEffect(() => {
        const customerId = parseNullableInt(quotation?.customerId);

        if (!customerId || customerId <= 0) {
            setSelectedCustomerDetails(null);
            setLoadedCustomerDetailsForId(null);
            return;
        }

        let isActive = true;

        const loadCustomerDetails = async () => {
            try {
                const requestKey = `customers:${customerId}`;
                const response = await getSharedRequest(requestKey, () => apiClient.get(`/customers/${customerId}`));
                if (!isActive) return;
                setSelectedCustomerDetails(response?.data ?? null);
                setLoadedCustomerDetailsForId(customerId);
            } catch (error) {
                console.error('Failed to load customer details:', error);
                if (!isActive) return;
                setSelectedCustomerDetails(null);
                setLoadedCustomerDetailsForId(customerId);
            }
        };

        loadCustomerDetails();

        return () => {
            isActive = false;
        };
    }, [quotation?.customerId]);

    useEffect(() => {
        const customerDeliveryAddressId = parseNullableInt(quotation?.customerDeliveryAddressId);
        setSelectedDeliveryAddressOption(customerDeliveryAddressId ? String(customerDeliveryAddressId) : '');
    }, [quotation?.customerDeliveryAddressId, quotation?.customerId]);

    if (loading || isSupplierDetailsLoading || isCustomerDetailsLoading) {
        return (
            <div className="pl-10 space-y-4 pt-1 ml-80 mr-60">
                <Skeleton height={30} width={420} className='mb-5' />
                <Skeleton height={220} />
                <Skeleton height={180} />
                <Skeleton height={160} />
            </div>
        );
    }

    if (!quotation) {
        return (
            <div className="pt-2 text-sm text-red-700">
                Kunde inte ladda offert.
                <button
                    type="button"
                    onClick={() => navigate('/order/quotations')}
                    className="ml-4 rounded-sm border border-gray-300 bg-white px-3 py-1 text-xs text-gray-700 hover:bg-gray-100"
                >
                    Tillbaka
                </button>
            </div>
        );
    }

    const customerContactPersonItems = Array.isArray(selectedCustomerDetails?.contactPersons)
        ? selectedCustomerDetails.contactPersons
            .map((item) => {
                const name = item?.name || item?.customerContactPersonName || item?.contactPerson || '';

                return {
                    id: name,
                    name,
                };
            })
            .filter((item) => item.name)
        : [];
    const customerDeliveryAddressItems = Array.isArray(selectedCustomerDetails?.deliveryAddresses)
        ? selectedCustomerDetails.deliveryAddresses.map((item, index) => {
            const addressSummary = [item?.address, item?.postalNr, item?.postalAddress, item?.country]
                .filter((part) => typeof part === 'string' && part.trim().length > 0)
                .join(', ');

            return {
                id: item?.id ?? `virtual-${index}`,
                name: item?.name || addressSummary || `Leveransadress ${index + 1}`,
            };
        })
        : [];
    const quotationRowReference = Array.isArray(quotation?.quotationRows)
        ? quotation.quotationRows.find((row) => row?.salesCurrencyName || row?.unitName || row?.unitMultiplicator != null)
        : null;
    const rowCurrencyName = quotationRowReference?.salesCurrencyName || quotation?.salesCurrencyName || '';
    const rowUnitName = quotationRowReference?.unitName || '';
    const numericUnitMultiplicator = Number(quotationRowReference?.unitMultiplicator);
    const hasUnitMultiplicator = Number.isFinite(numericUnitMultiplicator) && numericUnitMultiplicator > 0;
    const rowUnitLabel = [
        rowUnitName || null,
    ]
        .filter(Boolean)
        .join(' ');
    const priceColumnTitle = rowCurrencyName && rowUnitLabel
        ? `Pris ${rowCurrencyName}/${rowUnitLabel}`
        : `Pris ${rowCurrencyName}`.trim();

    return (
        <div className="relative flex flex-col h-full">
            <ConfirmationModal
                isOpen={showDeleteConfirm}
                onClose={() => setShowDeleteConfirm(false)}
                onConfirm={handleDelete}
                title="RADERA OFFERT"
                message={`Är du säker på att du vill radera offert ${quotation.id}? Åtgärden kan inte ångras.`}
                confirmText="Radera"
                cancelText="Avbryt"
                isDestructive={true}
            />

            <ConfirmationModal
                isOpen={showUnsavedWarning}
                onClose={handleUnsavedWarningAbort}
                onConfirm={handleUnsavedWarningConfirm}
                title="Osparade ändringar"
                message={unsavedWarningReason === 'print'
                    ? 'Du har osparade ändringar. Spara offert innan du skriver ut.'
                    : 'Det finns osparade ändringar, vill du ändå fortsätta?'}
                confirmText={unsavedWarningReason === 'print' ? '' : 'Fortsätt ändå'}
                cancelText="Avbryt"
                isDestructive={false}
            />

            <h2 className="ml-90 text-sm pt-2 pb-2 text-gray-700">
                {quotation?.id ? (
                    <>Offert <span className="ml-2 text-red-500">{quotation.id}</span></>
                ) : (
                    'Ny offert'
                )}
            </h2>

            <div className="flex h-full items-stretch">
                <div className="flex flex-col w-80 shrink-0 border-r border-gray-300 px-2 py-2 mb-5 mr-5">
                    <div className="space-y-3">
                        <h2 className="text-sm text-center text-gray-700">Info</h2>
                        <div className="space-y-2 text-xs text-gray-600">
                            {renderQuotationMetaRow('Skapad:', quotation?.createdAt, quotation?.createdByUserName)}
                            {renderQuotationMetaRow('Redigerad:', quotation?.editedAt, quotation?.editedByUserName)}
                            {/* {quotation?.createdAt && (
                                <div className="grid grid-cols-5 gap-4 mx-2">
                                    <div className="col-span-1"><span className="font-medium">Skapad:</span></div>
                                    <div className="col-span-4">{formatDateTime(quotation.createdAt)}</div>
                                </div>
                            )}
                            {quotation?.editedAt && (
                                <div className="grid grid-cols-5 gap-4 mx-2">
                                    <div className="col-span-1"><span className="font-medium">Redigerad:</span></div>
                                    <div className="col-span-4">{formatDateTime(quotation.editedAt)}</div>
                                </div>
                            )} */}
                            {/* <div className="grid grid-cols-5 gap-4 mx-2">
                                <div className="col-span-1"><span className="font-medium">Kund:</span></div>
                                <div className="col-span-4">{selectedCustomer?.name ?? quotation.customerName ?? 'Saknas'}</div>
                            </div>
                            <div className="grid grid-cols-5 gap-4 mx-2">
                                <div className="col-span-1"><span className="font-medium">Leverantör:</span></div>
                                <div className="col-span-4">{selectedSupplier?.name ?? 'Saknas'}</div>
                            </div>
                            {quotation?.answerDueDate && (
                                <div className="grid grid-cols-5 gap-4 mx-2">
                                    <div className="col-span-1"><span className="font-medium">Svar senast:</span></div>
                                    <div className="col-span-4">{formatDateTime(quotation.answerDueDate)}</div>
                                </div>
                            )} */}
                        </div>
                    </div>

                    <hr className="mt-5 border-gray-300 dark:border-white" />
                    <h2 className="text-sm text-center text-gray-700 mt-5">Meddelanden</h2>
                    {messages.length === 0 ? (
                        <p className='text-xs text-center font-light mt-4'>Inga meddelanden</p>
                    ) : (
                        <ul className="mt-2 space-y-2">
                            {[...messages].map((message, index) => (
                                <li
                                    key={index}
                                    className={`text-center text-xs p-2 rounded border border-gray-200 ${message.type === 'error'
                                        ? 'bg-red-100 text-red-700'
                                        : message.type === 'warning'
                                            ? 'bg-yellow-100 text-yellow-800'
                                            : 'bg-green-100 text-green-700'
                                        }`}
                                >
                                    {message.text}
                                </li>
                            ))}
                        </ul>
                    )}

                    <OrderNavigationTree
                        entityType="quotation"
                        entityId={Number.isInteger(quotation?.id) && quotation.id > 0 ? quotation.id : null}
                    />

                </div>

                <div className="flex-grow ps-4 pe-10 py-2 max-w-350">
                    <div className="flex justify-between w-full mb-5">
                        <div className='flex items-center space-x-4'>
                            <button
                                type='button'
                                onClick={handleBackClick}
                                className="shadow-md/30 text-xs text-white bg-gray-500 hover:bg-gray-700 px-5 p-[5px]"
                            >
                                Tillbaka
                            </button>
                            <button
                                type='button'
                                onClick={handleSave}
                                className="shadow-md/30 text-xs text-white bg-lime-700 hover:bg-lime-900 px-5 p-[5px]"
                            >
                                Spara
                            </button>
                            {quotation?.id !== 0 && (
                                <button
                                    type="button"
                                    onClick={() => void getPdf()}
                                    className="shadow-md/30 text-xs text-gray bg-blue-200 hover:bg-blue-300 px-4 py-[5px]"
                                >
                                    Skriv ut
                                </button>
                            )}
                        </div>
                        <div className='flex items-center space-x-4'>
                            {quotation?.id !== 0 && (
                                <button
                                    type="button"
                                    onClick={() => setShowDeleteConfirm(true)}
                                    className="shadow-md/30 text-xs text-white bg-red-700 hover:bg-red-800 px-5 p-[5px]"
                                >
                                    Radera
                                </button>
                            )}
                        </div>
                    </div>

                    <div className="ml-[-5px] w-200 mb-4 rounded-sm border border-gray-200 bg-gradient-to-br from-slate-50 via-white to-slate-100 px-5 py-4 shadow-sm">
                        <div className="grid grid-cols-[3fr_1fr]">
                            <div className="mt-0 grid grid-cols-1 gap-3 md:grid-cols-2 xl:grid-cols-3">
                                {renderReadOnlyInfoRow('Produkt', quotation?.product)}
                                {renderReadOnlyInfoRow('Material', quotation?.material)}
                                {/* {renderReadOnlyInfoRow('Tjocklek', quotation?.materialThickness)} */}
                                {renderReadOnlyInfoRow('Format', quotation?.format)}
                                {renderReadOnlyInfoRow('Färg', quotation?.color)}
                                {renderReadOnlyInfoRow('Konstruktion', quotation?.construction)}
                                {renderReadOnlyInfoRow('FSC', quotation?.isFSC ? 'Ja' : 'Nej')}
                            </div>
                            <div>
                                {renderReadOnlyInfoRow('Packning', 'todo')}
                            </div>
                        </div>
                    </div>

                    <div className="mt-10 grid w-full grid-cols-[max-content_minmax(0,1fr)] gap-x-25">
                        <span>
                            <div className="grid grid-cols-[380px_380px_300px] gap-x-20 gap-y-8">
                                <span>
                                    <p className='text-sm font-semibold text-gray-500 mb-4 pb-2 text-center border-b border-gray-300'>{quotation?.customerName || ''}</p>
                                    <LabeledReactSelect
                                        name='customerDeliveryAddressId'
                                        label='Lev. adress'
                                        value={quotation?.customerDeliveryAddressId || ''}
                                        items={customerDeliveryAddressItems}
                                        onChange={handleCustomerDeliveryAddressChange}
                                        labelWidth="w-20"
                                        margintop="2"
                                        allowRawValueLabel
                                    />
                                    <LabeledInput
                                        label=''
                                        value={quotation?.deliveryAddressName || ''}
                                        onChange={(value) => updateQuotation({ deliveryAddressName: value })}
                                        labelWidth="w-20"
                                        margintop="0"
                                    />
                                    <LabeledInput
                                        label=''
                                        value={quotation?.deliveryAddress || ''}
                                        onChange={(value) => updateQuotation({ deliveryAddress: value })}
                                        labelWidth="w-20"
                                        margintop="0"
                                    />
                                    <div className='flex space-x-1 w-full mt-[0px]'>
                                        <LabeledInput
                                            name='deliveryPostalNr'
                                            label=''
                                            value={quotation?.deliveryPostalNr || ''}
                                            onChange={(value) => updateQuotation({ deliveryPostalNr: value })}
                                            labelWidth="w-20"
                                            inputWidth="w-25"
                                            margintop="0"
                                            placeholder=""
                                        />
                                        <div className="w-full">
                                            <input
                                                name="deliveryPostalAddress"
                                                value={quotation?.deliveryPostalAddress || ''}
                                                onChange={(value) => updateQuotation({ deliveryPostalAddress: value })}
                                                className='text-xs w-full border border-gray-300 rounded-sm px-2 py-1 focus:outline-none bg-white'
                                            />

                                        </div>
                                    </div>
                                    <LabeledInput
                                        label=''
                                        value={quotation?.deliveryCountry || ''}
                                        onChange={(value) => updateQuotation({ deliveryCountry: value })}
                                        labelWidth="w-20"
                                        margintop="0"
                                    />
                                    <div className='flex items-center space-x-1 w-50 text-xs pt-[1px] pb-1'>
                                        <LabeledSwitch
                                            field='hideDeliveryAddressOnPrint'
                                            name='hideDeliveryAddressOnPrint'
                                            label='Dölj adress'
                                            value={quotation?.hideDeliveryAddressOnPrint || false}
                                            onChange={(rowId, field, checked) => updateQuotation({ [field]: checked })}
                                            labelWidth="w-20"
                                            marginTop={1}
                                        />
                                    </div>
                                    <LabeledInput
                                        label='Leveranstid'
                                        value={quotation?.timeOfDelivery || ''}
                                        onChange={(value) => updateQuotation({ timeOfDelivery: value })}
                                        labelWidth="w-20"
                                        margintop="0"
                                    />
                                    <div className='flex items-center space-x-1 w-50 text-xs pt-[1px]'>
                                        <label className="w-20 flex-none text-xs text-gray-700">Datum</label>
                                        <input
                                            type="date"
                                            value={formatDateInputValue(quotation?.date)}
                                            onChange={(event) => updateQuotation({ date: fromDateInputToSwedishIso(event.target.value) })}
                                            className="w-30 text-xs px-2 py-1 border border-gray-300 bg-white rounded-sm focus:outline-none focus:ring-1 focus:ring-green-500"
                                        />
                                    </div>
                                </span>

                                <span>
                                    <p className='text-sm font-semibold text-gray-500 mb-4 pb-2 text-center border-b border-gray-300'>{quotation?.selectedSupplierName ?? 'Saknas'}</p>
                                    <LabeledReactSelect
                                        name='yourReference'
                                        label='Er referens'
                                        value={quotation?.yourReference || ''}
                                        items={customerContactPersonItems}
                                        onChange={(value) => updateQuotation({ yourReference: value || '' })}
                                        labelWidth="w-20"
                                        margintop="2"
                                        allowRawValueLabel
                                    />
                                    <LabeledReactSelect
                                        name='ourReference'
                                        label='Vår referens'
                                        value={quotation?.ourReference || ''}
                                        items={legacyUserOptions}
                                        onChange={(value) => updateQuotation({ ourReference: value || '' })}
                                        labelWidth="w-20"
                                        margintop="0"
                                        allowRawValueLabel
                                    />
                                    <LabeledInput
                                        label='Lev.villkor'
                                        value={quotation?.termsOfDelivery || ''}
                                        onChange={(value) => updateQuotation({ termsOfDelivery: value })}
                                        labelWidth="w-20"
                                        margintop="0"
                                    />
                                    <LabeledTextArea
                                        label='Bet.villkor'
                                        value={quotation?.termsOfPayment || ''}
                                        onChange={(value) => updateQuotation({ termsOfPayment: value })}
                                        labelWidth="w-20"
                                        margintop="0"
                                        height="h-20"
                                    />
                                    <LabeledTextArea
                                        label='Meddelande'
                                        value={quotation?.message || ''}
                                        onChange={(value) => updateQuotation({ message: value })}
                                        labelWidth="w-20"
                                        margintop="0"
                                        height="h-15"
                                    />
                                </span>

                                <span>
                                    <p className="text-sm font-semibold text-gray-500 mb-1 pb-2 text-center">Offertrader</p>
                                    {Array.isArray(quotation?.quotationRows) && quotation.quotationRows.length > 0 && (
                                        <table className="w-full text-xs border-collapse">
                                            <thead>
                                                <tr className="border-b border-gray-300">
                                                    <th className="text-left font-medium text-gray-500 tracking-thin py-1 pr-6">Upplaga</th>
                                                    <th className="text-left font-medium text-gray-500 tracking-thin py-1 pr-6">{priceColumnTitle}</th>
                                                    <th className="text-left font-medium text-gray-500 tracking-thin py-1">Ta bort</th>
                                                </tr>
                                                <tr>
                                                    <td colSpan={3}><div className="border-t border-gray-300" /></td>
                                                </tr>
                                            </thead>
                                            <tbody className="[&>tr:first-child>td]:pt-2">
                                                {quotation.quotationRows.map((row) => (
                                                    <tr key={row.id} className="border-b border-gray-100">
                                                        <td className="py-1 pr-6 font-bold">{row.edition ?? ''}</td>
                                                        <td className="py-1 pr-6 font-bold">{row.price ?? ''}</td>
                                                        <td className="py-1">
                                                            <button
                                                                type="button"
                                                                onClick={() => handleDeleteRow(row.id)}
                                                                className="text-gray-600 hover:text-red-700"
                                                            >
                                                                Ta bort
                                                            </button>
                                                        </td>
                                                    </tr>
                                                ))}
                                            </tbody>
                                        </table>
                                    )}
                                </span>

                                <span className="col-span-2">
                                    <OrderCost
                                        quotationId={quotation?.id}
                                        rows={quotation?.orderCosts ?? []}
                                        costOptions={orderCostOptions}
                                        currencyOptions={currencyOptions}
                                        palletFormatId={quotation?.palletFormatId}
                                        eurPallet={quotation?.eurPallet}
                                        nrOfEurPallet={quotation?.nrOfEurPallet}
                                        eurPalletValue={quotation?.eurPalletValue}
                                        palletFormatOptions={palletFormatOptions}
                                        onPalletChange={handlePalletRowChange}
                                        onChange={handleOrderCostChange}
                                    />
                                </span>
                            </div>

                        </span>
                    </div>

                </div>
            </div>
        </div>
    );
};

export default Quotation;
