using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Econosys.Api.Models
{
    [Table("Inquiry")]
    public class Inquiry
    {
        [Key]
        [Column("lngInquiry_ID")]
        public int Id { get; set; }

        [Column("CompanyId")]
        public int CompanyId { get; set; }

        [Column("lngCalculation_ID")]
        public int? CalculationId { get; set; }

        [Column("bolAutoGenerated")]
        public bool AutoGenerated { get; set; }

        [Column("lngCustomer_ID")]
        public int? CustomerId { get; set; }

        [Column("strProduct")]
        [MaxLength(50)]
        public string? Product { get; set; }

        [Column("strMaterial")]
        [MaxLength(100)]
        public string? Material { get; set; }

        [Column("strMaterialThickness")]
        [MaxLength(50)]
        public string? MaterialThickness { get; set; }

        [Column("strFormat")]
        [MaxLength(50)]
        public string? Format { get; set; }

        [Column("strColor")]
        [MaxLength(50)]
        public string? Color { get; set; }

        [Column("strConstruction")]
        [MaxLength(50)]
        public string? Construction { get; set; }

        [Column("strCustomer")]
        [MaxLength(50)]
        public string? CustomerName { get; set; }

        [Column("strDeliveryAddressName")]
        [MaxLength(50)]
        public string? DeliveryAddressName { get; set; }

        [Column("strDeliveryAddress")]
        [MaxLength(50)]
        public string? DeliveryAddress { get; set; }

        [Column("strDeliveryPostalNr")]
        [MaxLength(50)]
        public string? DeliveryPostalNr { get; set; }

        [Column("strDeliveryPostalAddress")]
        [MaxLength(50)]
        public string? DeliveryPostalAddress { get; set; }

        [Column("strDeliveryCountry")]
        [MaxLength(50)]
        public string? DeliveryCountry { get; set; }

        [Column("strOurRef")]
        [MaxLength(50)]
        public string? OurRef { get; set; }

        [Column("strPreparation")]
        [MaxLength(50)]
        public string? Preparation { get; set; }

        [Column("strTimeOfDelivery")]
        [MaxLength(50)]
        public string? TimeOfDelivery { get; set; }

        [Column("lngSelectedInquiryRecipient_ID")]
        public int? SelectedInquiryRecipientId { get; set; }

        [Column("dteAnswerDueDate")]
        public DateTime? AnswerDueDate { get; set; }

        [Column("bolHideCustomerInfoOnPrint")]
        public bool HideCustomerInfoOnPrint { get; set; }

        [Column("dteCreated")]
        public DateTime? CreatedAt { get; set; }

        [Column("dteEdited")]
        public DateTime? EditedAt { get; set; }

        [Column("lngCreatedBy")]
        public int? CreatedBy { get; set; }

        [Column("lngEditedBy")]
        public int? EditedBy { get; set; }

        [Column("OldDbId")]
        public int? OldDbId { get; set; }

        [Column("CustomerDeliveryAddressId")]
        public int? CustomerDeliveryAddressId { get; set; }

        [Column("IsFSC")]
        public bool IsFSC { get; set; }

        public virtual Calculation? Calculation { get; set; }
        public virtual Customer? Customer { get; set; }
        public virtual InquiryRecipient? SelectedInquiryRecipient { get; set; }
        public virtual CustomerDeliveryAddress? CustomerDeliveryAddress { get; set; }
        [ForeignKey(nameof(CreatedBy))]
        public virtual LegacyUser? CreatedByUser { get; set; }
        [ForeignKey(nameof(EditedBy))]
        public virtual LegacyUser? EditedByUser { get; set; }
        public virtual ICollection<InquiryRecipient> InquiryRecipients { get; set; } = new List<InquiryRecipient>();
        public virtual ICollection<Quotation> Quotations { get; set; } = new List<Quotation>();
        public virtual ICollection<InquiryRow> InquiryRows { get; set; } = new List<InquiryRow>();
    }
}