namespace Econosys.Api.DTOs
{
    public class InquiryRowDto
    {
        public int Id { get; set; }
        public int? InquiryId { get; set; }
        public int? CalculationRowId { get; set; }
        public int? Edition { get; set; }
        public double? PurchasePrice { get; set; }
        public double? Freight { get; set; }
    }

    public class InquiryDto
    {
        public int Id { get; set; }
        public int CompanyId { get; set; }
        public int? CalculationId { get; set; }
        public string? PurchaseCurrencyName { get; set; }
        public string? SalesCurrencyName { get; set; }
        public bool AutoGenerated { get; set; }
        public int? CustomerId { get; set; }
        public string? Product { get; set; }
        public string? Material { get; set; }
        public string? MaterialThickness { get; set; }
        public string? Format { get; set; }
        public string? Color { get; set; }
        public string? Construction { get; set; }
        public string? CustomerName { get; set; }
        public string? DeliveryAddressName { get; set; }
        public string? DeliveryAddress { get; set; }
        public string? DeliveryPostalNr { get; set; }
        public string? DeliveryPostalAddress { get; set; }
        public string? DeliveryCountry { get; set; }
        public string? OurRef { get; set; }
        public string? Preparation { get; set; }
        public string? TimeOfDelivery { get; set; }
        public int? SelectedInquiryRecipientId { get; set; }
        public int? SelectedSupplierId { get; set; }
        public string? SelectedSupplierName { get; set; }
        public string? SelectedSupplierEmail { get; set; }
        public string? SelectedRecipientYourRef { get; set; }
        public string? SelectedRecipientTermsOfDelivery { get; set; }
        public string? SelectedRecipientTermsOfPayment { get; set; }
        public int? SelectedRecipientLanguageId { get; set; }
        public string? SelectedRecipientLanguageName { get; set; }
        public DateTime? AnswerDueDate { get; set; }
        public bool HideCustomerInfoOnPrint { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? EditedAt { get; set; }
        public int? CreatedBy { get; set; }
        public string? CreatedByUserName { get; set; }
        public int? EditedBy { get; set; }
        public string? EditedByUserName { get; set; }
        public int? CustomerDeliveryAddressId { get; set; }
        public bool IsFSC { get; set; }
        public string? CustomerEmail { get; set; }
        public List<InquiryRowDto> InquiryRows { get; set; } = new();
    }

    public class CreateInquiryRequest
    {
        public int CompanyId { get; set; }
        public int? CalculationId { get; set; }
        public bool AutoGenerated { get; set; }
        public int? CustomerId { get; set; }
        public string? Product { get; set; }
        public string? Material { get; set; }
        public string? MaterialThickness { get; set; }
        public string? Format { get; set; }
        public string? Color { get; set; }
        public string? Construction { get; set; }
        public string? CustomerName { get; set; }
        public string? DeliveryAddressName { get; set; }
        public string? DeliveryAddress { get; set; }
        public string? DeliveryPostalNr { get; set; }
        public string? DeliveryPostalAddress { get; set; }
        public string? DeliveryCountry { get; set; }
        public string? OurRef { get; set; }
        public string? Preparation { get; set; }
        public string? TimeOfDelivery { get; set; }
        public int? SelectedInquiryRecipientId { get; set; }
        public string? SelectedRecipientYourRef { get; set; }
        public string? SelectedRecipientTermsOfDelivery { get; set; }
        public string? SelectedRecipientTermsOfPayment { get; set; }
        public int? SelectedRecipientLanguageId { get; set; }
        public DateTime? AnswerDueDate { get; set; }
        public bool HideCustomerInfoOnPrint { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? EditedAt { get; set; }
        public int? CreatedBy { get; set; }
        public int? EditedBy { get; set; }
        public int? CustomerDeliveryAddressId { get; set; }
        public bool IsFSC { get; set; }
    }

    public class UpdateInquiryRequest : CreateInquiryRequest
    {
        public int Id { get; set; }
        public List<int> InquiryRowIds { get; set; } = new();
    }

    public class SearchInquiriesRequest
    {
        public string? SearchTerm { get; set; }
        public PaginationRequest? Pagination { get; set; }
        public List<SortRequest>? OrderBy { get; set; }
    }

    public class InquirySearchItemDto
    {
        public int Id { get; set; }
        public string? Product { get; set; }
        public string? CustomerName { get; set; }
        public string? SupplierName { get; set; }
        public string? Construction { get; set; }
        public string? Material { get; set; }
        public string? Format { get; set; }
        public string? SellerName { get; set; }
        public string? CreatedByName { get; set; }
        public DateTime? CreatedAt { get; set; }
        public DateTime? EditedAt { get; set; }
    }

}